apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: catalog-staging
spec:
  type: NodePort
  selector:
    app: catalog-api
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30081